import type { Metadata } from "next";
import "./globals.css";
import Header from "./shared/Header";
import { clashDisplay, silka, blauerNue } from '@/lib/fonts'
import Footer from "./shared/Footer";

export const metadata: Metadata = {
  title: "GROW HUBS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${clashDisplay.variable} ${silka.variable} ${blauerNue.variable}`} 
      >
        <div className="bg-[#020E1B]">
          <Header />
        </div>
        {children}
        {/* <Footer /> */}
      </body>
    </html>
  );
}