import type { Metadata } from "next";
import "./globals.css";
import Header from "./shared/Header";
import { clashDisplay, silka } from '@/lib/fonts'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${clashDisplay.variable} ${silka.variable}`}
      >
        <div className="bg-[#020E1B]">
          <Header />
        </div>
        {children}
      </body>
    </html>
  );
}
